# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-24 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0027_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='login',
        ),
    ]
