# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0031_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academia',
            name='id_academia',
        ),
        migrations.AddField(
            model_name='atleta',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='fed_judo.Usuario'),
        ),
    ]
