# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0032_auto_20171127_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='fed_judo.TipoUsuario'),
        ),
    ]
