# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0034_auto_20171127_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='eventos_cadastrado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fed_judo.Evento'),
        ),
    ]
