# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0039_auto_20171128_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='pontuacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.IntegerField(default=0),
        ),
    ]
