# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-30 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fed_judo', '0044_auto_20171130_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pontuacao',
            field=models.FloatField(default=0),
        ),
    ]
